apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-{{.Values.track}}
  labels:
    app: {{.Values.name}}
    track: {{.Values.track}}
data:
  API_URL: {{.Values.apiUrl}}
  APP_ENV: {{.Values.appEnv}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-{{.Values.track}}
  labels:
    app: {{.Values.name}}
    track: {{.Values.track}}
    version: {{.Values.version}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
      track: {{.Values.track}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
        track: {{.Values.track}}
        version: {{.Values.version}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{.Values.name}}-{{.Values.track}}
