apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: multiservice
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{.Values.name}}-{{.Values.track}}
  labels:
    app: {{.Values.name}}
    track: {{.Values.track}}
spec:
  host: {{.Values.name}}
  subsets:
  - name: {{.Values.name}}-{{.Values.track}}
    labels:
      track: {{.Values.track}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.name}}-{{.Values.track}}
  labels:
    app: {{.Values.name}}
    track: {{.Values.track}}
spec:
  hosts:
  - "*"
  gateways:
  - multiservice
  http:
  - name: {{.Values.name}}-{{.Values.track}}-header
    match:
    - uri:
        exact: /{{.Values.endpoint}}
    - headers:
        track:
          exact: {{.Values.track}}
    rewrite:
      uri: /rpc
    route:
    - destination:
        host: {{.Values.name}}
        subset: {{.Values.name}}-{{.Values.track}}
  - name: {{.Values.name}}-{{.Values.track}}-primary
    match:
    - uri:
        exact: /{{.Values.endpoint}}
    rewrite:
      uri: /rpc
    route:
    - destination:
        host: {{.Values.name}}
        subset: {{.Values.name}}-primary
  - name: {{.Values.name}}-{{.Values.track}}-default
    route:
    - destination:
        host: default-http-backend.kube-system
