namespace: default
apiUrl: http://<your-istio-cluster-ingress-host-or-ip>
replicas: 1

name: multiservice-a  # Change to multiservice-b and multiservice-c when deploying those images
image: <your-repo>/multiservice/a:v1
version: v1  # Change to v2 or v3 when deploying images with those tags
track: primary # Change to custom header value when deploying a custom track
endpoint: a  # Change to b or c when deploying those images
appEnv: primary-a  # Any string, that will be mirrored back in the payload response. Represents config changes rather than image/tag changes
